### ISSUE TITLE
Error 500 federated SPARQL

### ISSUE THREAD

**Issue by mfiguer** [labra/shaclex#75]
I have a problem executing a federated query at http://shaclex.herokuapp.com/query. I got the following error: " HTTP 500 error making the query: SPARQL Request Failed".

The data set in N3 notation is in  http://clasificadospropiedades.cl/Hermes/data/NewsArticles.N3 and I use the "By Input" option with the following code

```
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX schema:<http://schema.org/>
PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbr:<http://dbpedia.org/resource/>

SELECT DISTINCT ?noticia ?titulo ?autor ?cuerpo ?persona ?resumen_persona ?descripcion
WHERE
{
   { ?noticia a schema:NewsArticle .
        ?noticia schema:headline ?titulo .
        ?noticia schema:author ?autor .
        ?noticia schema:articleBody ?cuerpo .
        FILTER REGEX(?cuerpo,"Chilesaurus"^^xsd:string).  
        SERVICE <http://dbpedia.org/sparql> {
		dbr:Chilesaurus rdfs:comment ?descripcion .
         ?persona a dbo:Person .
        ?persona dbo:abstract ?resumen_persona .
       FILTER REGEX(?resumen_persona,"Chilesaurus"^^xsd:string). 
       
      } 
  
  }
}
```

**Comment by labra** [comment]
I tested that SPARQL query using [Apache Jena's command line SPARQL tool](https://jena.apache.org/documentation/tools/index.html) and it gives the following error:

```
$ sparql --query news.sparql --data news.ttl
Query Exeception
HttpException: 500 HTTP 500 error making the query: SPARQL Request Failed
	at org.apache.jena.sparql.engine.http.HttpQuery.rewrap(HttpQuery.java:371)
	at org.apache.jena.sparql.engine.http.HttpQuery.execGet(HttpQuery.java:337)
	at org.apache.jena.sparql.engine.http.HttpQuery.exec(HttpQuery.java:288)
        . . .
       at arq.query.queryExec(query.java:221)
	at arq.query.exec(query.java:153)
	at jena.cmd.CmdMain.mainMethod(CmdMain.java:93)
	at jena.cmd.CmdMain.mainRun(CmdMain.java:58)
	at jena.cmd.CmdMain.mainRun(CmdMain.java:45)
	at arq.sparql.main(sparql.java:28)
```

so I think the problem is in how Jena processes the federated query. Shaclex just leverages on Jena for SPARQL processing so there is nothing we can do here.
